
version: 2

models:
  - name: customer
    columns:
      - name: CUSTOMER_ID
        data_tests:
          - unique
          - not_null     
      - name: NAME
        data_tests:
          - not_null  
      - name: GENDER
        data_tests:
          - accepted_values: 
              values: ['Male','Female']   

  - name: order_target
    columns:
      - name: ORDER_ID
        data_tests:
          - unique 
      - name: CUSTOMER_ID
        data_tests:
          - relationships: 
              to: ref('customer')
              field: CUSTOMER_ID                             

  - name: sales
    columns:
      - name: UNIT_PRICE
        data_tests:
          - positive_amount_test

sources:         
  - name: staging 
    database: db1
    schema: source
    tables:
       - name: employees 
       - name: countries 
       - name: DEPARTMENTS
       - name: LOCATIONS
       - name: CUSTOMER_INFO
       - name: ORDER_INFO
       - name: SALES_INFO